# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - peekit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://lptccapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ee67c3db95704f318b9519b8fa444bf3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8e94b5216ddc4f698fdf0598f3f501ee }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: lptccapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ee67c3db95704f318b9519b8fa444bf3 }}/site-peek:${{ github.sha }}
        file: ./Peek/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'peekit'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_662fab763db149b99dfa4cc52473b2f0 }}
        images: 'lptccapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ee67c3db95704f318b9519b8fa444bf3 }}/site-peek:${{ github.sha }}'